import { Component } from '@angular/core';
import { MatDialog } from '@angular/material/dialog';
import { StudentsFormComponent } from './components/students-form/students-form.component';
import { Student } from './models';
import { MatTableDataSource } from '@angular/material/table';

@Component({
  selector: 'app-students',
  templateUrl: './students.component.html',
  styleUrls: ['./students.component.scss'],
})
export class StudentsComponent {
  students = new MatTableDataSource<Student>([
    {
      id: 1,
      name: 'Georgiana',
      lastname: 'Klaff',
      email: 'gklaff0@wunderground.com',
      gender: 3,
      birthdate: new Date(2022, 11, 10),
    },
    {
      id: 2,
      name: 'Joseito',
      lastname: 'Grosvener',
      email: 'jgrosvener1@sogou.com',
      gender: 2,
      birthdate: new Date(2023, 6, 12),
    },
    {
      id: 3,
      name: 'Shanon',
      lastname: 'McGlade',
      email: 'smcglade2@amazon.com',
      gender: 1,
      birthdate: new Date(2023, 5, 18),
    },
    {
      id: 4,
      name: 'Felicio',
      lastname: 'Whiterod',
      email: 'fwhiterod3@cbslocal.com',
      gender: 2,
      birthdate: new Date(2023, 5, 24),
    },
    {
      id: 5,
      name: 'Therine',
      lastname: 'Ledgard',
      email: 'tledgard4@dropbox.com',
      gender: 1,
      birthdate: new Date(2023, 8, 13),
    },
    {
      id: 6,
      name: 'Helen-elizabeth',
      lastname: 'Pes',
      email: 'hpes5@jiathis.com',
      gender: 1,
      birthdate: new Date(2022, 11, 8),
    },
    {
      id: 7,
      name: 'Quintus',
      lastname: 'Toombs',
      email: 'qtoombs6@mediafire.com',
      gender: 2,
      birthdate: new Date(2023, 9, 24),
    },
    {
      id: 8,
      name: 'Lucio',
      lastname: 'Lewing',
      email: 'llewing7@washingtonpost.com',
      gender: 2,
      birthdate: new Date(2023, 6, 28),
    },
    {
      id: 9,
      name: 'Sanson',
      lastname: 'Grouen',
      email: 'sgrouen8@apple.com',
      gender: 2,
      birthdate: new Date(2022, 10, 28),
    },
    {
      id: 10,
      name: 'Elva',
      lastname: 'McCullum',
      email: 'emccullum9@mlb.com',
      gender: 1,
      birthdate: new Date(2023, 6, 8),
    },
    {
      id: 11,
      name: 'Germana',
      lastname: 'MacConchie',
      email: 'gmacconchiea@ucsd.edu',
      gender: 1,
      birthdate: new Date(2023, 4, 17),
    },
    {
      id: 12,
      name: 'Dannie',
      lastname: 'Touret',
      email: 'dtouretb@hugedomains.com',
      gender: 1,
      birthdate: new Date(2023, 4, 10),
    },
    {
      id: 13,
      name: 'Kelsy',
      lastname: 'Andries',
      email: 'kandriesc@noaa.gov',
      gender: 1,
      birthdate: new Date(2023, 8, 4),
    },
    {
      id: 14,
      name: 'Sib',
      lastname: 'Woolhouse',
      email: 'swoolhoused@ebay.com',
      gender: 1,
      birthdate: new Date(2023, 3, 16),
    },
    {
      id: 15,
      name: 'Dall',
      lastname: 'Glazebrook',
      email: 'dglazebrooke@prweb.com',
      gender: 2,
      birthdate: new Date(2023, 6, 29),
    },
    {
      id: 16,
      name: 'Abie',
      lastname: 'Curley',
      email: 'acurleyf@arstechnica.com',
      gender: 2,
      birthdate: new Date(2023, 7, 8),
    },
    {
      id: 17,
      name: 'Zandra',
      lastname: 'Fell',
      email: 'zfellg@1und1.de',
      gender: 1,
      birthdate: new Date(2023, 5, 28),
    },
    {
      id: 18,
      name: 'Katerina',
      lastname: 'Pozzi',
      email: 'kpozzih@nhs.uk',
      gender: 1,
      birthdate: new Date(2022, 12, 22),
    },
    {
      id: 19,
      name: 'Keen',
      lastname: 'Popland',
      email: 'kpoplandi@deviantart.com',
      gender: 2,
      birthdate: new Date(2023, 7, 13),
    },
    {
      id: 20,
      name: 'Geno',
      lastname: 'Finlaison',
      email: 'gfinlaisonj@devhub.com',
      gender: 2,
      birthdate: new Date(2023, 7, 10),
    },
    {
      id: 21,
      name: 'Griffie',
      lastname: 'Didsbury',
      email: 'gdidsburyk@storify.com',
      gender: 2,
      birthdate: new Date(2023, 6, 4),
    },
    {
      id: 22,
      name: 'Netty',
      lastname: 'Nuschke',
      email: 'nnuschkel@uiuc.edu',
      gender: 1,
      birthdate: new Date(2023, 1, 19),
    },
    {
      id: 23,
      name: 'Dionisio',
      lastname: 'Brookbank',
      email: 'dbrookbankm@ocn.ne.jp',
      gender: 3,
      birthdate: new Date(2023, 6, 22),
    },
    {
      id: 24,
      name: 'Natka',
      lastname: 'Saterweyte',
      email: 'nsaterweyten@acquirethisname.com',
      gender: 1,
      birthdate: new Date(2023, 1, 10),
    },
    {
      id: 25,
      name: 'Wells',
      lastname: 'Dahler',
      email: 'wdahlero@yellowbook.com',
      gender: 2,
      birthdate: new Date(2023, 1, 12),
    },
    {
      id: 26,
      name: 'Anastasia',
      lastname: 'Ridsdale',
      email: 'aridsdalep@blogs.com',
      gender: 1,
      birthdate: new Date(2022, 12, 5),
    },
    {
      id: 27,
      name: 'Marielle',
      lastname: 'Wooddisse',
      email: 'mwooddisseq@gnu.org',
      gender: 1,
      birthdate: new Date(2023, 4, 26),
    },
    {
      id: 28,
      name: 'Joshua',
      lastname: 'Dunnet',
      email: 'jdunnetr@list-manage.com',
      gender: 3,
      birthdate: new Date(2022, 11, 17),
    },
    {
      id: 29,
      name: 'Manny',
      lastname: 'Learned',
      email: 'mlearneds@japanpost.jp',
      gender: 2,
      birthdate: new Date(2023, 3, 1),
    },
    {
      id: 30,
      name: 'Giorgia',
      lastname: 'Kingdon',
      email: 'gkingdont@example.com',
      gender: 1,
      birthdate: new Date(2023, 5, 15),
    },
    {
      id: 31,
      name: 'Maddalena',
      lastname: 'Davidof',
      email: 'mdavidofu@51.la',
      gender: 1,
      birthdate: new Date(2023, 7, 14),
    },
    {
      id: 32,
      name: 'Bertrando',
      lastname: 'Humpherston',
      email: 'bhumpherstonv@hatena.ne.jp',
      gender: 2,
      birthdate: new Date(2023, 6, 20),
    },
    {
      id: 33,
      name: 'Thaine',
      lastname: 'Ginglell',
      email: 'tginglellw@wikimedia.org',
      gender: 2,
      birthdate: new Date(2023, 6, 22),
    },
    {
      id: 34,
      name: 'Daphne',
      lastname: 'Dowding',
      email: 'ddowdingx@twitter.com',
      gender: 1,
      birthdate: new Date(2023, 5, 6),
    },
    {
      id: 35,
      name: 'Myrah',
      lastname: 'Huard',
      email: 'mhuardy@reddit.com',
      gender: 1,
      birthdate: new Date(2023, 5, 6),
    },
    {
      id: 36,
      name: 'Donnajean',
      lastname: "O'Brogane",
      email: 'dobroganez@samsung.com',
      gender: 1,
      birthdate: new Date(2023, 7, 29),
    },
    {
      id: 37,
      name: 'Gael',
      lastname: 'Schulkins',
      email: 'gschulkins10@nymag.com',
      gender: 2,
      birthdate: new Date(2023, 6, 18),
    },
    {
      id: 38,
      name: 'Kimmy',
      lastname: 'Fenne',
      email: 'kfenne11@thetimes.co.uk',
      gender: 1,
      birthdate: new Date(2022, 10, 27),
    },
    {
      id: 39,
      name: 'Harp',
      lastname: 'Curl',
      email: 'hcurl12@disqus.com',
      gender: 2,
      birthdate: new Date(2023, 8, 4),
    },
    {
      id: 40,
      name: 'Ramon',
      lastname: 'MacCrann',
      email: 'rmaccrann13@livejournal.com',
      gender: 3,
      birthdate: new Date(2023, 7, 16),
    },
    {
      id: 41,
      name: 'Alexei',
      lastname: 'Haversum',
      email: 'ahaversum14@pinterest.com',
      gender: 2,
      birthdate: new Date(2023, 4, 14),
    },
    {
      id: 42,
      name: 'Florie',
      lastname: 'Nortunen',
      email: 'fnortunen15@elegantthemes.com',
      gender: 1,
      birthdate: new Date(2023, 6, 12),
    },
    {
      id: 43,
      name: 'Menard',
      lastname: 'Marchington',
      email: 'mmarchington16@sphinn.com',
      gender: 2,
      birthdate: new Date(2022, 12, 20),
    },
    {
      id: 44,
      name: 'Christi',
      lastname: 'McCurdy',
      email: 'cmccurdy17@jigsy.com',
      gender: 1,
      birthdate: new Date(2023, 1, 4),
    },
    {
      id: 45,
      name: 'Quinton',
      lastname: 'Cecil',
      email: 'qcecil18@latimes.com',
      gender: 2,
      birthdate: new Date(2023, 8, 16),
    },
    {
      id: 46,
      name: 'Barnabe',
      lastname: 'Gulliver',
      email: 'bgulliver19@mail.ru',
      gender: 2,
      birthdate: new Date(2022, 11, 20),
    },
    {
      id: 47,
      name: 'Law',
      lastname: 'Bagworth',
      email: 'lbagworth1a@jalbum.net',
      gender: 2,
      birthdate: new Date(2022, 11, 20),
    },
    {
      id: 48,
      name: 'Roxi',
      lastname: 'Kerby',
      email: 'rkerby1b@pen.io',
      gender: 3,
      birthdate: new Date(2023, 3, 16),
    },
    {
      id: 49,
      name: 'Winifred',
      lastname: 'Riccelli',
      email: 'wriccelli1c@deliciousdays.com',
      gender: 1,
      birthdate: new Date(2023, 3, 30),
    },
    {
      id: 50,
      name: 'Nady',
      lastname: 'Donaghy',
      email: 'ndonaghy1d@github.com',
      gender: 1,
      birthdate: new Date(2023, 1, 10),
    },
    {
      id: 51,
      name: 'Derril',
      lastname: 'Mee',
      email: 'dmee1e@storify.com',
      gender: 2,
      birthdate: new Date(2023, 7, 30),
    },
    {
      id: 52,
      name: 'Avivah',
      lastname: 'Chilcott',
      email: 'achilcott1f@so-net.ne.jp',
      gender: 1,
      birthdate: new Date(2023, 1, 1),
    },
    {
      id: 53,
      name: 'Kort',
      lastname: 'Sleford',
      email: 'ksleford1g@ibm.com',
      gender: 3,
      birthdate: new Date(2023, 8, 21),
    },
    {
      id: 54,
      name: 'Lizbeth',
      lastname: 'Ruffles',
      email: 'lruffles1h@uol.com.br',
      gender: 3,
      birthdate: new Date(2023, 8, 9),
    },
    {
      id: 55,
      name: 'Edithe',
      lastname: 'Kiddie',
      email: 'ekiddie1i@nymag.com',
      gender: 1,
      birthdate: new Date(2023, 9, 18),
    },
    {
      id: 56,
      name: 'Gennifer',
      lastname: 'Lougheid',
      email: 'glougheid1j@slate.com',
      gender: 1,
      birthdate: new Date(2022, 10, 31),
    },
    {
      id: 57,
      name: 'Farrand',
      lastname: 'Braga',
      email: 'fbraga1k@tripadvisor.com',
      gender: 1,
      birthdate: new Date(2023, 8, 4),
    },
    {
      id: 58,
      name: 'Ingunna',
      lastname: 'Woodburn',
      email: 'iwoodburn1l@people.com.cn',
      gender: 1,
      birthdate: new Date(2022, 10, 18),
    },
    {
      id: 59,
      name: 'Erinn',
      lastname: 'Keyhoe',
      email: 'ekeyhoe1m@aol.com',
      gender: 1,
      birthdate: new Date(2022, 10, 15),
    },
    {
      id: 60,
      name: 'Goldina',
      lastname: 'Gallaher',
      email: 'ggallaher1n@google.pl',
      gender: 1,
      birthdate: new Date(2023, 4, 13),
    },
    {
      id: 61,
      name: 'Gearard',
      lastname: 'Jozsef',
      email: 'gjozsef1o@dot.gov',
      gender: 2,
      birthdate: new Date(2023, 4, 30),
    },
    {
      id: 62,
      name: 'Chicky',
      lastname: 'Stallen',
      email: 'cstallen1p@ovh.net',
      gender: 1,
      birthdate: new Date(2022, 12, 11),
    },
    {
      id: 63,
      name: 'Gaynor',
      lastname: 'Gantz',
      email: 'ggantz1q@ebay.com',
      gender: 1,
      birthdate: new Date(2023, 1, 26),
    },
  ]);
  constructor(private matDialog: MatDialog) {}

  openStudentDialog(): void {
    this.matDialog
      .open(StudentsFormComponent)
      .afterClosed()
      .subscribe({
        next: (v) => {
          if (!!v) {
            this.students.data = [
              ...this.students.data,
              {
                ...v,
                id: new Date().getTime(),
              },
            ];
          }
        },
      });
  }

  onDeleteStudent(studentId: number): void {
    if (confirm('Está seguro?'))
      this.students.data = this.students.data.filter((s) => s.id !== studentId);
  }

  onEditStudent(student: Student): void {
    this.matDialog
      .open(StudentsFormComponent, {
        data: student,
      })
      .afterClosed()
      .subscribe({
        next: (v) => {
          if (!!v) {
            this.students.data = this.students.data.map((s) =>
              s.id === student.id ? { ...s, ...v } : s
            );
          }
        },
      });
  }
}
